db.uri=jdbc:postgresql://localhost:2345/game
db.user=postgres
db.password=postgres
db.driver=org.postgresql.Driver

hibernate.connection.url=jdbc:postgresql://localhost:2345/game
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.username=postgres
hibernate.connection.password=postgres
show_sql=true
format_sql=true
